name: "rpmlint"
description: "run rpmlint"
author: "@shogo82148"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    default: "${{ github.token }}"
    required: true
  rpmlint_flags:
    description: "Additional rpmlint flags"
    default: ""
    required: false
runs:
  using: "docker"
  image: 'docker://ghcr.io/shogo82148/actions-rpmlint:v0.2.0@sha256:c948ca7fd3470e2ab9781803e90007fafa361bbe0cdc49fe9ca13dbb50441b9a'
branding:
  color: red
  icon: check-circle
