name: 'rpmlint with reviewdog'
description: 'run rpmlint with reviewdog'
author: '@shogo82148'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
    required: true
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'rpmlint'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: true
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
    required: true
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
    required: true
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
    required: true
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false
  rpmlint_flags:
    description: 'Additional rpmlint flags'
    default: ''
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: red
  icon: check-circle
